name: gentle_lints
description: A comprehensive set of lint rules suitable for both Dart and Flutter projects.
version: 1.0.0

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  lints: ^2.0.1
  dart_code_metrics: ^4.19.2
